[package]
name = "zomboid_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "24.0"
winit = { version = "0.30", features = ["rwh_06"] }
pollster = "0.4"
bytemuck = { version = "1.19", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
pathfinding = "4.14"
image = { version = "0.25", default-features = false, features = ["png"] }
bevy = { version = "0.19.1", default-features = false }
block-mesh = "0.2.0"
tokio = { version = "1.43", features = ["rt-multi-thread", "net", "sync", "time", "io-util", "macros"] }
