use crate::engine::items::ItemType;

pub fn get_item_texture_bytes(item: ItemType) -> Option<&'static [u8]> {
    match item {
        ItemType::Apple => Some(include_bytes!("../../../assets/textures/item/apple.png")),
        ItemType::Bread => Some(include_bytes!("../../../assets/textures/item/bread.png")),
        ItemType::Bucket => Some(include_bytes!("../../../assets/textures/item/bucket.png")),
        ItemType::WaterBucket => Some(include_bytes!("../../../assets/textures/item/water_bucket.png")),
        ItemType::DiamondSword => Some(include_bytes!("../../../assets/textures/item/diamond_sword.png")),
        ItemType::DiamondPickaxe => Some(include_bytes!("../../../assets/textures/item/diamond_pickaxe.png")),
        ItemType::Coal => Some(include_bytes!("../../../assets/textures/item/coal.png")),
        ItemType::Stick => Some(include_bytes!("../../../assets/textures/item/stick.png")),
        ItemType::IronIngot => Some(include_bytes!("../../../assets/textures/item/iron_ingot.png")),
        ItemType::Porkchop => Some(include_bytes!("../../../assets/textures/item/porkchop.png")),
        ItemType::CookedPorkchop => Some(include_bytes!("../../../assets/textures/item/cooked_porkchop.png")),
        ItemType::Beef => Some(include_bytes!("../../../assets/textures/item/beef.png")),
        ItemType::CookedBeef => Some(include_bytes!("../../../assets/textures/item/cooked_beef.png")),
        ItemType::Mutton => Some(include_bytes!("../../../assets/textures/item/mutton.png")),
        ItemType::CookedMutton => Some(include_bytes!("../../../assets/textures/item/cooked_mutton.png")),
        ItemType::Leather => Some(include_bytes!("../../../assets/textures/item/leather.png")),
        ItemType::WhiteWool => Some(include_bytes!("../../../assets/textures/block/white_wool.png")),
        ItemType::WoodenPickaxe => Some(include_bytes!("../../../assets/textures/item/wooden_pickaxe.png")),
        ItemType::StonePickaxe => Some(include_bytes!("../../../assets/textures/item/stone_pickaxe.png")),
        ItemType::IronPickaxe => Some(include_bytes!("../../../assets/textures/item/iron_pickaxe.png")),
        ItemType::WoodenSword => Some(include_bytes!("../../../assets/textures/item/wooden_sword.png")),
        ItemType::StoneSword => Some(include_bytes!("../../../assets/textures/item/stone_sword.png")),
        ItemType::IronSword => Some(include_bytes!("../../../assets/textures/item/iron_sword.png")),
        ItemType::Diamond => Some(include_bytes!("../../../assets/textures/item/diamond.png")),
        ItemType::WoodenAxe => Some(include_bytes!("../../../assets/textures/item/wooden_axe.png")),
        ItemType::StoneAxe => Some(include_bytes!("../../../assets/textures/item/stone_axe.png")),
        ItemType::IronAxe => Some(include_bytes!("../../../assets/textures/item/iron_axe.png")),
        ItemType::DiamondAxe => Some(include_bytes!("../../../assets/textures/item/diamond_axe.png")),
        ItemType::WoodenShovel => Some(include_bytes!("../../../assets/textures/item/wooden_shovel.png")),
        ItemType::StoneShovel => Some(include_bytes!("../../../assets/textures/item/stone_shovel.png")),
        ItemType::IronShovel => Some(include_bytes!("../../../assets/textures/item/iron_shovel.png")),
        ItemType::DiamondShovel => Some(include_bytes!("../../../assets/textures/item/diamond_shovel.png")),
        ItemType::WoodenHoe => Some(include_bytes!("../../../assets/textures/item/wooden_hoe.png")),
        ItemType::StoneHoe => Some(include_bytes!("../../../assets/textures/item/stone_hoe.png")),
        ItemType::IronHoe => Some(include_bytes!("../../../assets/textures/item/iron_hoe.png")),
        ItemType::DiamondHoe => Some(include_bytes!("../../../assets/textures/item/diamond_hoe.png")),
        ItemType::Block(crate::world::block::BlockType::Torch) => Some(include_bytes!("../../../assets/textures/block/torch.png")),
        _ => None,
    }
}
